# Generated by Django 3.1.4 on 2020-12-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
