# Generated by Django 3.1.4 on 2020-12-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='exploitreport',
            old_name='warzone',
            new_name='target_warzone',
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='what_can_u_do',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='what_will_u_do',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='search_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='vpn_ip',
            field=models.CharField(max_length=20),
        ),
    ]
