# Generated by Django 3.1.4 on 2020-12-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20201226_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploitreport',
            old_name='what_can_u_do',
            new_name='expected',
        ),
        migrations.RenameField(
            model_name='exploitreport',
            old_name='what_will_u_do',
            new_name='follow_up',
        ),
    ]
