# Generated by Django 3.1.4 on 2020-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_exploitreport_target_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='target_port',
            field=models.CharField(max_length=10),
        ),
    ]
