# Generated by Django 3.1.4 on 2020-12-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201226_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploitreport',
            name='image',
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='expected',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='follow_up',
            field=models.CharField(max_length=1000),
        ),
    ]
