# Generated by Django 3.1.4 on 2020-12-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20201227_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploitreport',
            old_name='state',
            new_name='status',
        ),
    ]
