# Generated by Django 3.1.4 on 2021-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_user_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='status',
            field=models.CharField(default='待審核', max_length=10),
        ),
        migrations.AlterField(
            model_name='inforcollectreport',
            name='status',
            field=models.CharField(default='待審核', max_length=10),
        ),
    ]
