# Generated by Django 3.1.5 on 2021-01-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20210105_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploitreport',
            name='target_warzone',
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='IC_type',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='excute_location',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='source',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='exploitreport',
            name='target_version',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
