# Generated by Django 3.1.5 on 2021-01-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20210112_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='IC_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='excute_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_version',
            field=models.CharField(max_length=50),
        ),
    ]
