# Generated by Django 3.1.5 on 2021-01-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20210113_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
