# Generated by Django 3.1.5 on 2021-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20210113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.JSONField(default=' ', max_length=1000),
        ),
    ]
