# Generated by Django 3.1.5 on 2021-01-13 06:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20210113_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
