# Generated by Django 3.1.5 on 2021-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20210113_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
