# Generated by Django 3.1.5 on 2021-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20210113_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.JSONField(max_length=50),
        ),
    ]
