# Generated by Django 3.1.5 on 2021-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20210113_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploitreport',
            old_name='con',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='inforcollectreport',
            name='content',
            field=models.JSONField(max_length=1000),
        ),
    ]
