# Generated by Django 3.1.5 on 2021-01-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20210116_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
