# Generated by Django 3.1.5 on 2021-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='image',
            field=models.ImageField(upload_to='EX_report_img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='userphoto/'),
        ),
    ]
