# Generated by Django 3.1.5 on 2021-02-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20210218_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
