# Generated by Django 3.1.5 on 2021-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_user_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='inforcollectreport',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
