# Generated by Django 3.1.5 on 2021-02-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_auto_20210220_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='exploitreport',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='ex_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.exploitreport'),
        ),
    ]
