# Generated by Django 3.1.5 on 2021-02-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_auto_20210220_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='ic_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.inforcollectreport'),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.user'),
        ),
    ]
