# Generated by Django 3.1.5 on 2021-02-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0039_images_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='content_id',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
