# Generated by Django 3.1.5 on 2021-03-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_images_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.AlterField(
            model_name='images',
            name='content',
            field=models.CharField(max_length=10),
        ),
    ]
