# Generated by Django 3.1.5 on 2021-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_auto_20210603_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='excute_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='weakness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
