# Generated by Django 3.1.5 on 2021-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0044_auto_20210603_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitreport',
            name='IC_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='admin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='excute_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='excute_location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='expected',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='follow_up',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='people',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='search_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_ip',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_port',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='use',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='vpn_ip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='weakness',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
