# Generated by Django 3.1.5 on 2021-06-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0046_auto_20210604_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='ic_post',
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='excute_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exploitreport',
            name='target_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='InforCollectReport',
        ),
    ]
