# Generated by Django 3.2.4 on 2021-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0048_auto_20210608_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
