# Generated by Django 3.2.4 on 2021-06-24 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0050_alter_images_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitedJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('target_name', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(blank=True, max_length=100000)),
                ('status', models.CharField(blank=True, default='待審核', max_length=10)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='uni_judge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.unitedjudge'),
        ),
    ]
